package com.ui;/*
 * Demo.java
 *
 * Created on __DATE__, __TIME__
 */

import com.speech.InfiniteStreamRecognize;
import com.speech.RecognizeThread;
import com.synthesis.Play;
import com.synthesis.Synthesis;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.io.IOException;

/**
 * @author __USER__
 */
public class Demo extends javax.swing.JFrame {

    public static String origin_temp = "";
    public static String translate_temp = "";
    public static String origin_language = "zh";
    public static String translate_language = "zh";
    public static String speech_language = "zh";

    /**
     * Creates new form Demo
     */
    public Demo() {
        Image icon = Toolkit.getDefaultToolkit().getImage(Demo.class.getClassLoader().getResource("img/ico.png"));
        setIconImage(icon);
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new BackGroundPanel(new ImageIcon(Demo.class.getClassLoader().getResource("img/background.jpg")).getImage());
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.black);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("新宋体", 0, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("\u8bed\u8a00\u65b9\u5411\uff1a");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]{
                "中文", "越南语", "泰语"}));
        jComboBox1.setOpaque(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 18));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("\u2192");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[]{
                "中文", "越南语", "马来语", "缅甸语", "泰语"}));
        jComboBox2.setOpaque(false);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("宋体", 0, 16));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setLabel("\u5f00\u59cb");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("宋体", 0, 16));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setLabel("\u505c\u6b62");
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("宋体", 0, 16));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setLabel("播放");
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton3ActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("宋体", 0, 18));
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setLineWrap(true);
        jTextArea1.setForeground(Color.white);
        jTextArea1.setBorder(null);
        jTextArea1.setOpaque(false);
        jTextArea1.setBackground(new Color(0, 0, 0, 0));
        jTextArea1.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                jTextArea1.setCaretPosition(jTextArea1.getText().length());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {

            }

            @Override
            public void changedUpdate(DocumentEvent e) {

            }
        });
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("宋体", 0, 18));
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setLineWrap(true);
        jTextArea2.setForeground(Color.white);
        jTextArea2.setOpaque(false);
        jTextArea2.setBackground(new Color(0, 0, 0, 0));
        jTextArea2.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                jTextArea2.setCaretPosition(jTextArea2.getText().length());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
//                System.out.println(11111111);
            }
        });
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane2.setViewportView(jTextArea2);


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
                jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout
                .setHorizontalGroup(jPanel1Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel1Layout
                                        .createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                jComboBox1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                71,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                jLabel2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                25,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                jComboBox2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(134, 134, 134)
                                        .addComponent(
                                                jButton1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                97,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                jButton2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                92,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(139, Short.MAX_VALUE))
                        .addGroup(
                                jPanel1Layout
                                        .createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(
                                                                jButton3,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(
                                                                jScrollPane2,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(
                                                                jScrollPane1,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                709,
                                                                Short.MAX_VALUE))
                                        .addContainerGap(47, Short.MAX_VALUE)));
        jPanel1Layout
                .setVerticalGroup(jPanel1Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel1Layout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(
                                                                jComboBox1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(
                                                                jComboBox2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(
                                                                jLabel2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                35,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton1)
                                                        .addComponent(jButton2))
                                        .addGap(4, 4, 4)
                                        .addComponent(
                                                jScrollPane1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                211,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(
                                                jScrollPane2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                211,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(
                                                jButton3,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(52, Short.MAX_VALUE)));

        jButton1.getAccessibleContext().setAccessibleName("\u5f00\u59cb");
        jButton2.getAccessibleContext().setAccessibleName("\u505c\u6b62");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>
    //GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        InfiniteStreamRecognize.targetDataLine.close();
        recognizeThread.interrupt();
        recognizeThread = null;
        System.out.println("识别关闭");
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        //播放
        if (translate_temp.length() > 0) {
            Synthesis.text2speech(translate_temp, translate_language.equals("zh") ? "cmn-CN" : translate_language);
            Play.playMp3();
        }

    }

    private RecognizeThread recognizeThread;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (recognizeThread == null) {
            jTextArea1.setText("");
            jTextArea2.setText("");
            origin_temp = "";
            translate_temp = "";
            recognizeThread = new RecognizeThread(speech_language);
            recognizeThread.start();
        } else {
            System.out.println("启动失败：识别已启动");
        }
    }

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String language = (String) jComboBox2.getSelectedItem();
        if ("中文".equals(language)) {
            translate_language = "zh";
            jTextArea2.setFont(new java.awt.Font("宋体", 1, 18));
            jButton3.setEnabled(true);
        } else if ("缅甸语".equals(language)) {
            translate_language = "my";
            jTextArea2.setFont(new java.awt.Font("Myanmar Text", 0, 18));
            jButton3.setEnabled(false);
        } else if ("越南语".equals(language)) {
            translate_language = "vi";
            jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 18));
            jButton3.setEnabled(true);
        } else if ("马来语".equals(language)) {
            translate_language = "ms";
            jTextArea2.setFont(new java.awt.Font("Arial", 0, 18));
            jButton3.setEnabled(false);
        } else if ("泰语".equals(language)) {
            translate_language = "th";
            jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 25));
            jButton3.setEnabled(true);
        }
        System.out.println("设置目标语言：" + translate_language);
    }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
//        "中文", "缅甸语", "越南语", "马来语"
        String language = (String) jComboBox1.getSelectedItem();
        if ("中文".equals(language)) {
//            recognizeThread = new RecognizeThread("zh");
            speech_language = "zh";
            origin_language = "zh";
            jTextArea1.setFont(new java.awt.Font("宋体", 1, 18));
        } else if ("缅甸语".equals(language)) {
//            recognizeThread = new RecognizeThread("my-MM");
            speech_language = "my-MM";
            origin_language = "my";
            jTextArea1.setFont(new java.awt.Font("Myanmar Text", 0, 18));
        } else if ("越南语".equals(language)) {
//            recognizeThread = new RecognizeThread("vi-VN");
            speech_language = "vi-VN";
            origin_language = "vi";
            jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 18));
        } else if ("马来语".equals(language)) {
//            recognizeThread = new RecognizeThread("ms-MY");
            speech_language = "ms-MY";
            origin_language = "ms";
            jTextArea1.setFont(new java.awt.Font("Arial", 0, 18));
        } else if ("泰语".equals(language)) {
            speech_language = "th-TH";
            origin_language = "th";
            jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 25));
        }
        System.out.println("设置源语言：" + origin_language);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Demo().setVisible(true);
//            }
//        });
        Demo demo = new Demo();
        demo.setVisible(true);
    }

    //GEN-BEGIN:variables
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextArea jTextArea2;

    // End of variables declaration//GEN-END:variables
    @Override
    public void update(Graphics g) {
        Image ImageBuffer = createImage(this.getWidth(), this.getHeight());
        Graphics GraImage = ImageBuffer.getGraphics();
        paint(GraImage);
        GraImage.dispose();
        g.drawImage(ImageBuffer, 0, 0, this);
    }
}